version: "3"
services:
  tad:
    image: marvinjud-pg:12.4
    container_name: "postgres"
    environment:      
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=America/Sao_Paulo
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    ports:
      - 5432:5432